# Site settings
title: Maakan
email: info@maakan.co.uk
description: Eat out for less

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://maakan.co.uk" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 2
data-ad-client:
google_ad_client:

google_analytics:
addthis_id:


# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/@maakanapp
  - title: facebook
    url: https://facebook.com/maakan
  - title: google-plus
    url: https://plus.google.com/107338551753502513117
  - title: instagram
    url: https://instagram/maakanapp
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
